name: Dependency Check Sarif

on:
  push:
    branches:
      - master

jobs:

  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    
    runs-on: ubuntu-latest

    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Dependency Check
      run: |
        docker run --rm -v $PWD:/usr/src/app --user $(id -u):$(id -g) -w /usr/src/app owasp/dependency-check:latest --format SARIF --out /usr/src/app/result.sarif --nvdApiKey $NVD_API_KEY --scan .
        ls -a
    - name: Upload scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'result.sarif'
