name: Dependency Check Sarif

on:
  push:
    branches:
      - master

jobs:

  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    
    runs-on: ubuntu-latest

    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Dependency Check
      run: |
        docker run owasp/dependency-check:latest --nvdApiKey $NVD_API_KEY --format SARIF --out result.sarif --scan .
        ls -a

    - name: Upload scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: '/src/result.sarif'
